apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payments
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "false"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: /
  SERVER_PORT: "8080"
