apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: payments
type: Opaque
# Valores em base64: echo -n 'valor' | base64
# IMPORTANTE: substitua pelos valores reais antes de aplicar
stringData:
  db-url: jdbc:postgresql://db.efzyetzqaglykuxhbvjm.supabase.co:5432/postgres?sslmode=require
  db-username: postgres
  db-password: EkhGLi22PmU!!68
  rabbitmq-host: capybara.lmq.cloudamqp.com
  rabbitmq-username: pvxqgwmm
  rabbitmq-password: s6C7CklOH_5U3N0GBQd3IUCI--N8xk4E
