apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: payments
type: Opaque
# Valores em base64: echo -n 'valor' | base64
# IMPORTANTE: substitua pelos valores reais antes de aplicar
stringData:
  db-url: jdbc:postgresql://postgres-service:5432/payment_db
  db-username: payment_user
  db-password: payment_secret
  rabbitmq-host: rabbitmq-service
  rabbitmq-username: guest
  rabbitmq-password: guest
